# Generated by Django 6.1 on 2026-08-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Price in INR (paise-free)')),
                ('category', models.CharField(choices=[('Classics', 'Classics'), ('Self-Help', 'Self-Help'), ('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Sci-Fi'), ('Biography', 'Biography'), ('Business', 'Business')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_ebook', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, default='Bestseller', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_class', models.CharField(default='offer-card-1', max_length=30)),
                ('discount', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=30)),
                ('expiry_label', models.CharField(default='3 days', max_length=30)),
                ('hours_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('weekly_change', models.CharField(default='+0%', max_length=10)),
                ('is_hot', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending', to='books.book')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
