# Generated by Django 6.1.1 on 2026-09-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=15, help_text='Inventory stock count'),
        ),
    ]
